
# GETTING DATA
DATA=trees


# DATA VIEWING
str(DATA)
summary(DATA)
is.na(DATA)



# DIMENSIONALITY REDUCTION

DATACLEANED=DATA

# IMPUTING OUTLIERS AND FEEDING NAs TO THEM
{
OUTLIERS=NULL
for (i in 1:ncol(DATACLEANED))
{
  if(class(DATACLEANED[,i])=='numeric'||class(DATACLEANED[,i])=='integer')
  {
    if (length((boxplot(DATACLEANED[,i])$out))==0)
    {
      print ('NO OUTLIERS')
    }else {
      print ('OUTLIERS')
      OUTLIERS=boxplot(DATACLEANED[,i], plot=FALSE)$out
      DATACLEANED[which(DATACLEANED[,i] %in% OUTLIERS),i]=NA
      OUTLIERS=NULL
    }
  }else{
    print ("NOT NUMERIC")
  }
}
}
summary(DATACLEANED)
DATANOOUTLIER=DATACLEANED





# DATA SUBSETTING AND PREPARATION
set.seed(1234)
ind=sample(2,nrow(trees),replace=T,prob=c(0.6,0.4))
TRAINING=trees[ind==1,]
TESTING=trees[ind==2,]

# CREATING DECISION TREE MODEL
MODEL=lm(Volume~.,data=TRAINING)
summary(MODEL)

# PLOTTING MODEL
p=plot(TRAINING$Girth,TRAINING$Volume)
abline(MODEL,col='red')

# CREATING MODEL FOR SIGNIFICANT COLUMN
MODEL=lm(Volume~Girth,data=TRAINING)
MODEL
summary(MODEL)

# PLOTTING MODEL AGAIN FOR SIGNIFICANT COLUMN
q=plot(TRAINING$Girth,TRAINING$Volume)
abline(MODEL,col='red')

# PREDICTION
summary(trees)
PREDICTION=predict(MODEL,TESTING)
PREDICTION
DIFFERENCE=abs(TESTING[,3]-PREDICTION)
ERROR_PERCENTAGE=DIFFERENCE/TESTING[,3]*100
ERROR_PERCENTAGE
ACCURACY_PERCENTAGE=100-ERROR_PERCENTAGE
(cbind(ACTUAL=TESTING[,3],PREDICTED=PREDICTION,ERROR=DIFFERENCE,ERROR_PERCENTAGE,ACCURACY_PERCENTAGE))

mean(ACCURACY_PERCENTAGE)


# CROSS VALIDATION
table(PREDICTION,TESTING[,2])
# CHECKING ACCURACY PERCENTAGE
(ACCURACY=PREDICTION/TESTING[3]*100) 
mean(ACCURACY[,1])
(mean(TESTING[,3])-mean(PREDICTION))/mean(TESTING[,3])*100

